color: red
fieldLayouts:
  68354ade-90fd-468f-ab02-5bb3ccdd0045:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef98a3ad-8e85-447b-810b-cea79974e705
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f0acbfff-6b9e-4817-9f2c-7181d9a26493 # Video ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccc4fa6d-0ce9-4d4f-a8d9-424ad42a71b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01d733bf-a346-483a-9ba2-1cce0f886a51 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e411ab9-ce89-452e-b6d6-d7f998a257ec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48211880-92aa-4d63-adc6-0532b84306f4
        userCondition: null
handle: youtubeVideo
hasTitleField: false
icon: film
name: 'Youtube Video'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
