columnSuffix: null
handle: videoId
instructions: 'Video ID is extracted from the URL after `?v=`'
name: 'Video ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
